apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
       - imagePullPolicy: {{ .Values.image.pullPolicy }}
         name: techtrends
         image: {{ .Values.image.repository }} : {{ .Values.image.tag }}
         livenessProbe:
           initialDelaySeconds: 1
           periodSeconds: 2
           timeoutSeconds: 1
           successThreshold: 1
           failureThreshold: 1
           httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort.port }}
         readinessProbe:
           initialDelaySeconds: 1
           periodSeconds: 2
           timeoutSeconds: 1
           successThreshold: 1
           failureThreshold: 1
           httpGet:
             path: {{ .Values.readinessProbe.path }}
             port: {{ .Values.containerPort.port }}   
