apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: aykamal/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
        - containerPort: 3111
        hostname: myapplication1.com
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests: 
              memory: "64Mi"
              cpu: "250m"
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 3111
         readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 3111   
            
