namespace:
  name: sandbox
 
service:
  port: 4111
  targetport: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: aykamal/techtrends 
  tag: v1.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

containerPort:
  port: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
