namespace:
  name: sendbox
 
service:
  port: 4111
  targetport: 3111
  protocol: tcp
  type: ClusterIP

image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

containerPort:
  port: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
