
## MOVE THIS FILE to `.github/workflows/docker-build.yaml` TO EXECUTE IT

## This is a basic workflow to help you get started with Actions

name: TechTrends - Package with Docker

# Controls when the action will run. Triggers the workflow on push or pull reques
# events but only for the master branch
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       
      # -
       # name: Checkouts
       # uses: actions/checkout@v2
       -
        name: echo variables 2
        run: |
              echo $GITHUB_REF
       -     
          name: Docker meta
          id: meta
          uses: docker/metadata-action@v3
          with:
             images: aykamal/techtrends:v1.0
             tags: |
              type=semver,pattern={{major}}.{{minor}}
              
      
        
          
